# Generated by Django 4.2.7 on 2023-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
